# Generated by Django 5.0 on 2024-02-13 11:45

import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='If possible, upload an image that is least 120 pixels wide.', null=True, upload_to=teacher.models.avatar_path, verbose_name='تصویر پروفایل'),
        ),
    ]
