# Generated by Django 5.0 on 2024-01-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_sold_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sale_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد فروش'),
        ),
    ]
