# Generated by Django 5.0 on 2024-01-03 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='عنوان')),
                ('is_child', models.BooleanField(default=False, verbose_name='فرزند است')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='ﺎﺳﻼﮔ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='images/course-banners/', verbose_name='بنر')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.coursecategory', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی دوره ها',
                'verbose_name_plural': 'دسته بندی های دوره ها',
            },
        ),
        migrations.CreateModel(
            name='ShortVideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='عنوان')),
                ('is_child', models.BooleanField(default=False, verbose_name='فرزند است')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='ﺎﺳﻼﮔ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='images/short-video-banners/', verbose_name='بنر')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.shortvideocategory', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی ویدیو های کوتاه',
                'verbose_name_plural': 'دسته بندی های ویدیو های کوتاه',
            },
        ),
    ]
