# Generated by Django 5.0 on 2024-01-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/course-banner/', verbose_name='بنر'),
        ),
    ]
