# Generated by Django 5.0 on 2024-01-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_coursecategory_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortvideocategory',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='images/category/short-video-banner/', verbose_name='بنر'),
        ),
    ]
