# Generated by Django 5.0 on 2024-02-17 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_coursecategory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='coursecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='shortvideocategory',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='shortvideocategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین بروزرسانی'),
        ),
    ]
