# Generated by Django 5.0 on 2024-01-03 20:31

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('course', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='اسلاگ')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('video', models.FileField(upload_to='videos/courses/', verbose_name='ویدیو')),
                ('section', models.CharField(max_length=2, verbose_name='شماره قسمت')),
                ('banner', models.ImageField(upload_to='images/course-videos/', verbose_name='بنر')),
                ('courses', models.ManyToManyField(related_name='videos', to='course.course', verbose_name='دوره ها')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)svideos', to='teacher.teacher', verbose_name='آموزگار')),
            ],
            options={
                'verbose_name': 'ویدیو دوره ها',
                'verbose_name_plural': 'ویدیو های دوره ها',
            },
        ),
        migrations.CreateModel(
            name='ShortVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True, verbose_name='اسلاگ')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ساخت')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ آخرین بروزرسانی')),
                ('video', models.FileField(upload_to='videos/shorts/', verbose_name='ویدیو')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('banner', models.ImageField(upload_to='images/course-videos/', verbose_name='بنر')),
                ('categories', models.ManyToManyField(related_name='short_videos', to='category.shortvideocategory', verbose_name='دسته بندی ها')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)svideos', to='teacher.teacher', verbose_name='آموزگار')),
            ],
            options={
                'verbose_name': 'ویدیو کوتاه',
                'verbose_name_plural': 'ویدیو های کوتاه',
            },
        ),
    ]
