# Generated by Django 5.0 on 2024-01-04 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_coursevideo_price_coursevideo_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortvideo',
            name='price',
        ),
    ]
